/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author Alexios
 */
public class frmAdm extends javax.swing.JFrame {

    /**
     * Creates new form frmAdm
     */
    public frmAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadUsuario = new javax.swing.JButton();
        Checkin = new javax.swing.JButton();
        CadBrindes = new javax.swing.JButton();
        CadEventos1 = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADM DO SISTEMA");
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CadUsuario.setText("Cadastrar Usuarios");
        CadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, -1));

        Checkin.setText("Check-In");
        Checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckinActionPerformed(evt);
            }
        });
        getContentPane().add(Checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, -1));

        CadBrindes.setText("Cadastrar Brindes");
        CadBrindes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBrindesActionPerformed(evt);
            }
        });
        getContentPane().add(CadBrindes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, -1));

        CadEventos1.setText("Cadastrar Eventos");
        CadEventos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadEventos1ActionPerformed(evt);
            }
        });
        getContentPane().add(CadEventos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, -1));

        Sair.setBackground(new java.awt.Color(255, 204, 102));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uni_externa22800px.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 300));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void CheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckinActionPerformed
       frmCheckinAdm AdmCheckin = new frmCheckinAdm();
       AdmCheckin.setLocationRelativeTo(null);
       AdmCheckin.setVisible(true);
    }//GEN-LAST:event_CheckinActionPerformed

    private void CadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadUsuarioActionPerformed
        frmCadAdm aCadAdm = new frmCadAdm();
        aCadAdm.setLocationRelativeTo(null);
        aCadAdm.setVisible(true);
    }//GEN-LAST:event_CadUsuarioActionPerformed

    private void CadBrindesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBrindesActionPerformed
        frmCadBrindes aCadBrinde = new frmCadBrindes();
        aCadBrinde.setLocationRelativeTo(null);
        aCadBrinde.setVisible(true);
    }//GEN-LAST:event_CadBrindesActionPerformed

    private void CadEventos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadEventos1ActionPerformed
        frmCadEventos aCadEvento = new frmCadEventos();
        aCadEvento.setLocationRelativeTo(null);
        aCadEvento.setVisible(true);
    }//GEN-LAST:event_CadEventos1ActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadBrindes;
    private javax.swing.JButton CadEventos1;
    private javax.swing.JButton CadUsuario;
    private javax.swing.JButton Checkin;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
